# Generated by Django 2.2 on 2021-06-21 18:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tile',
            name='title',
        ),
        migrations.AddField(
            model_name='tile',
            name='launch_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tile',
            name='status',
            field=models.CharField(choices=[(0, 'Live'), (1, 'Pending,'), (2, 'Achieved')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tile',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[(0, 'Survey'), (1, 'Discussion,'), (2, 'Diary')], max_length=10),
        ),
    ]
