# Generated by Django 2.2 on 2021-06-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210621_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(0, 'Survey'), (1, 'Discussion'), (2, 'Diary')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Live'), (1, 'Pending'), (2, 'Achieved')], max_length=10),
        ),
    ]
