# Generated by Django 2.2 on 2021-06-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210621_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.IntegerField(choices=[(1, 'Survey'), (2, 'Discussion'), (3, 'Diary')]),
        ),
        migrations.AlterField(
            model_name='tile',
            name='status',
            field=models.IntegerField(choices=[(1, 'Live'), (2, 'Pending'), (3, 'Achieved')]),
        ),
        migrations.RemoveField(
            model_name='tile',
            name='task',
        ),
        migrations.AddField(
            model_name='tile',
            name='task',
            field=models.ManyToManyField(to='app.Task'),
        ),
    ]
