# Generated by Django 2.2 on 2021-06-21 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210621_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tile',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='tile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Tile'),
            preserve_default=False,
        ),
    ]
