# Generated by Django 2.2 on 2021-06-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210621_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
