# Generated by Django 2.2 on 2021-06-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210621_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
