# Generated by Django 2.2 on 2021-06-21 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210621_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Tile'),
        ),
    ]
